# Generated by Django 5.0.4 on 2024-04-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_name_client_first_name_client_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.CharField(default='company', max_length=100),
            preserve_default=False,
        ),
    ]
