# Generated by Django 5.0.4 on 2024-04-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='scorm_count',
        ),
    ]
