# Generated by Django 5.0.4 on 2024-04-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0010_clientuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="clientuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientuser",
            name="scrom_consumed",
            field=models.IntegerField(default=0),
        ),
    ]
