# Generated by Django 5.0.4 on 2024-04-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_clientuser_email_clientuser_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientuser",
            old_name="scrom_consumed",
            new_name="scorm_consumed",
        ),
    ]
