# Generated by Django 4.2.11 on 2024-05-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_client_lms_api_key_client_lms_api_key_secret_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="lms_api_key_secret",
            new_name="lms_api_secret",
        ),
    ]
