# Generated by Django 4.2.11 on 2024-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0016_rename_lms_api_key_secret_client_lms_api_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientuser",
            name="launch_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
