# Generated by Django 4.2.11 on 2024-05-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0017_clientuser_launch_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
