# Generated by Django 4.2.11 on 2024-05-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0018_alter_client_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserScormStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion", models.CharField(max_length=255)),
                ("total_time", models.CharField(max_length=255)),
                ("score", models.CharField(max_length=255)),
                (
                    "client_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.clientuser",
                    ),
                ),
            ],
        ),
    ]
