# Generated by Django 4.2.11 on 2024-06-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0019_userscormstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="userscormstatus",
            name="attempt",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="userscormstatus",
            name="complete_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userscormstatus",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userscormstatus",
            name="satisfied_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userscormstatus",
            name="scorm_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userscormstatus",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userscormstatus",
            name="client_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="clients.clientuser",
            ),
        ),
        migrations.AlterField(
            model_name="userscormstatus",
            name="completion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userscormstatus",
            name="score",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="userscormstatus",
            name="total_time",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
