# Generated by Django 4.2.11 on 2024-06-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scorm", "0014_course_syncing_status"),
        ("clients", "0021_userscormstatus_scorm_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userscormstatus",
            name="scorm_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scorm.scormassignment",
            ),
        ),
    ]
