# Generated by Django 4.2.11 on 2024-06-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scorm", "0014_course_syncing_status"),
        ("clients", "0022_userscormstatus_scorm_assignment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userscormstatus",
            old_name="scorm_id",
            new_name="_scorm_id",
        ),
        migrations.RemoveField(
            model_name="userscormstatus",
            name="scorm_assignment",
        ),
        migrations.AddField(
            model_name="userscormstatus",
            name="scorm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="scorm.scormasset",
            ),
        ),
    ]
