# Generated by Django 4.2.11 on 2024-06-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0023_rename_scorm_id_userscormstatus__scorm_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userscormstatus",
            name="scorm",
        ),
    ]
