# Generated by Django 4.2.11 on 2024-06-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0025_remove_userscormstatus_completion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientuser",
            name="launch_url",
        ),
    ]
