# Generated by Django 5.0.4 on 2024-04-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0002_scormasset_scorm_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormasset',
            name='scorm_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
