# Generated by Django 5.0.4 on 2024-04-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0003_alter_scormasset_scorm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormasset',
            name='extension',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='scormasset',
            name='filename',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scormasset',
            name='full_path_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scormasset',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scormasset',
            name='reference',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scormasset',
            name='scormdir',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scormasset',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='scormasset',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='scormasset',
            name='zipfilename',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scormasset',
            name='zippath',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scormasset',
            name='scorm_file',
            field=models.FileField(upload_to='scorm_uploads_zipped/'),
        ),
    ]
