# Generated by Django 5.0.4 on 2024-04-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0005_remove_scormasset_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scormasset',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
