# Generated by Django 5.0.4 on 2024-04-12 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_created_at_client_scorm_count'),
        ('scorm', '0006_alter_scormasset_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scormasset',
            name='license_seats',
        ),
        migrations.CreateModel(
            name='ScormAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('number_of_seats', models.IntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('scorm_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorm.scormasset')),
            ],
        ),
    ]
