# Generated by Django 5.0.4 on 2024-04-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorm', '0007_remove_scormasset_license_seats_scormassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scormasset',
            name='access_validity_period',
        ),
        migrations.RemoveField(
            model_name='scormasset',
            name='clients',
        ),
        migrations.AddField(
            model_name='scormassignment',
            name='validity_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scormassignment',
            name='validity_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
