# Generated by Django 5.0.4 on 2024-04-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorm", "0008_remove_scormasset_access_validity_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scormassignment",
            name="client_scorm_file",
            field=models.FileField(
                blank=True, null=True, upload_to="client_scorm_files/"
            ),
        ),
    ]
