# Generated by Django 5.0.4 on 2024-04-15 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0010_clientuser"),
        ("scorm", "0009_scormassignment_client_scorm_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserScormMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scorm.scormassignment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.clientuser",
                    ),
                ),
            ],
        ),
    ]
