# Generated by Django 4.2.11 on 2024-05-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scorm", "0010_userscormmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("cover_photo", models.URLField()),
                ("short_description", models.CharField(max_length=250)),
                ("long_description", models.TextField()),
                (
                    "scorm_assets",
                    models.ManyToManyField(blank=True, to="scorm.scormasset"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(choices=[("scorm", "SCORM")], max_length=50)),
                ("title", models.CharField(max_length=200)),
                ("file", models.URLField()),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="scorm.course",
                    ),
                ),
            ],
        ),
    ]
