# Generated by Django 4.2.11 on 2024-05-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorm", "0012_scormasset_cover_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scormasset",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="scorm_uploads/cover_photos/default.png",
                null=True,
                upload_to="scorm_uploads/cover_photos/",
            ),
        ),
    ]
