# Generated by Django 4.2.11 on 2024-05-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorm", "0013_alter_scormasset_cover_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="syncing_status",
            field=models.BooleanField(default=False),
        ),
    ]
