# Generated by Django 4.2.11 on 2024-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorm", "0014_course_syncing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userscormmapping",
            name="launch_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
